XIQ-9899, openAPI spec for Alert XAPI
extremenetworks/ExtremeCloudIQ-OpenAPI pull request #12
Opened 2022-09-01 09:41 UTC by jma-522

2022-09-01 19:35 UTC, Shangquan-Wen commented
The PR does not pass lint check, please fix them and resubmit the PR:
```
validating openapi/alert/openapi.yaml...
[1] openapi/alert/paths/alerts_count-by-{group}.yaml:5:[16](https://github.com/extremenetworks/ExtremeCloudIQ-OpenAPI/runs/8132202205?check_suite_focus=true#step:8:17) at #/get/description

Operation description must be at least 20 characters and end with a full stop.

3 |   - Alert
4 | summary: Count the alerts by different grouping
5 | description: Count the number of alerts and events based on Severity, Category,
6 |   and Alert Type
7 | externalDocs:
8 |   description: API Reference

Error was generated by the operation-description assertion rule.


[2] openapi/alert/components/schemas/XiqAlertGroup.yaml:1:1 at #/

The field `name` must be present on this level.

1 | type: string
2 | enum:
… | < 2 more lines >
5 |   - ALERT_TYPE

Error was generated by the spec rule.


[3] openapi/alert/components/schemas/XiqAlertGroup.yaml:1:1 at #/

The field `in` must be present on this level.

1 | type: string
2 | enum:
… | < 2 more lines >
5 |   - ALERT_TYPE

1 | type: string
2 | enum:
… | < 2 more lines >
5 |   - ALERT_TYPE

Error was generated by the parameter-description rule.


[8] openapi/alert/paths/alerts_count-by-{group}.yaml:12:3 at #/get/parameters

The operation does not define the path parameter `{group}` expected by path `/alerts/count-by-{group}`.

10 |     https://extremecloudiq.com/api-docs/api-reference.html#_count_the_alerts_by_group
11 | operationId: countAlertsByGroup
12 | parameters:
13 |   - $ref: ../components/schemas/XiqAlertGroup.yaml
14 |   - $ref: ../../common/components/parameters/query/startTime.yaml

Error was generated by the path-parameters-defined rule.
```

2022-09-06 17:21 UTC, Shangquan-Wen commented on openapi/alert/components/schemas/XiqAlert.yaml
> +      source_name:
It's better to include `source` object here, including id, type, name, etc.

2022-09-15 04:43 UTC, jma-522 commented on openapi/alert/components/schemas/XiqAlert.yaml
> +      source_name:
done

2022-09-15 05:13 UTC, jma-522 commented on openapi/alert/components/schemas/XiqAlertSeverity.yaml
> +  - WARNING
done

2022-09-15 05:42 UTC, xwhong submitted a review, later dismissed

2022-09-15 22:29 UTC, Shangquan-Wen requested changes

2022-09-15 22:29 UTC, Shangquan-Wen commented on openapi/alert/components/schemas/XiqAlertSource.yaml
> +allOf:
Just define as a `type`, no need to add `AllOf` here.

2022-09-15 22:29 UTC, Shangquan-Wen commented on openapi/authentication/paths/login.yaml
> +    - BearerAuth: []
No need to add security for `login`.

2022-09-15 22:40 UTC, jma-522 commented on openapi/alert/components/schemas/XiqAlertSource.yaml
> +allOf:
good catch

2022-09-15 22:40 UTC, jma-522 commented on openapi/authentication/paths/login.yaml
> +    - BearerAuth: []
If I don't add it, the pnpm lint or build will fail

2022-09-15 22:56 UTC, Shangquan-Wen commented on openapi/authentication/paths/login.yaml
> +    - BearerAuth: []
In this case, you should add `security: []` to indicate this is a public API instead of requiring `BearerAuth`.

2022-09-15 23:31 UTC, jma-522 commented on openapi/authentication/paths/login.yaml
> +    - BearerAuth: []
Done

2022-09-15 23:38 UTC, Shangquan-Wen requested changes

2022-09-15 23:38 UTC, Shangquan-Wen commented on openapi/authorization/paths/auth_apitoken.yaml
> +  security: []
This endpoint should use `BearerAuth` instead of disabling Auth.

2022-09-16 01:27 UTC, jma-522 commented on openapi/authorization/paths/auth_apitoken.yaml
> +  security: []
ok

2022-09-16 01:52 UTC, ycao-extreme commented on openapi/authorization/paths/auth_apitoken.yaml
> +  security:
We don't need to add it, otherwise it will be a secured endpoint in swagger-ui.

2022-09-16 01:55 UTC, ycao-extreme commented on openapi/authentication/paths/login.yaml
> +    - BearerAuth: []
The login should not be secured, we don't need to add it, even if you add `security: []` it will show as locked endpoint in swagger-ui.

2022-09-16 02:55 UTC, ycao-extreme commented
Suggest change the target branch to [FEATURE-XIQ-API-22R7](https://github.com/extremenetworks/ExtremeCloudIQ-OpenAPI/tree/FEATURE-XIQ-API-22R7)

2022-11-09 19:04 UTC, Shangquan-Wen approved these changes

2022-12-13 19:25 UTC, Shangquan-Wen approved these changes

2022-12-13 19:27 UTC, merged